x-net-config: &net-config
  network_mode: host
  ipc: host
  env_file: net.env

x-gpu-config: &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=:99
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

services:
  webots-headless:
    privileged: true
    restart: unless-stopped
    build:
      context: .
    environment: # NOTE: .env file should be present in the root directory
      - TRANSITIVE_ID=${TRANSITIVE_ID}
      - TRANSITIVE_TOKEN=${TRANSITIVE_TOKEN}
      - TR_DISPLAYNAME=${TR_DISPLAYNAME}
    <<: [*net-config, *gpu-config]

  webots-mcs-bridge:
    build:
      context: ./external/mcs_bridge
      dockerfile: Dockerfile
    <<: [*net-config]
    env_file:
      - ./external/mcs_bridge/.env
    command: ["--bridge-type", "ros2"]
    depends_on:
      - webots-headless
