x-net-config: &net-config
  network_mode: host
  ipc: host
  env_file: net.env

x-gpu-config: &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=:0
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

services:
  webots-headless:
    build: .
    <<: [ *net-config, *gpu-config ]
    volumes:
      - /dev/dri:/dev/dri
